# Generated by Django 6.0.5 on 2026-05-15 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_auto_20260515_1719'),
    ]

    operations = [
    ]
