# Generated by Django 6.0.5 on 2026-05-15 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_auto_20260515_1719'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentmodel',
            name='original_filename',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
